ShoppingApplication.Webb/Models/CouponDto.cs
namespace ShoppingApplication.Webb.Models
{
    public class CouponDto
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public double DiscountAmount { get; set; }
        public int MinAmount { get; set; }
    }
}

ShoppingApplication.Webb/Models/ErrorViewModel.cs
namespace ShoppingApplication.Webb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShoppingApplication.Webb/Models/RequestDto.cs
using ShoppingApplication.Webb.Utility;
using System.Security.AccessControl;
using static ShoppingApplication.Webb.Utility.SD;

namespace ShoppingApplication.Webb.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET; // API type eka get,put, post delet. default thiyanne get eka. enum field ekak add krala thiyenne
        public string Url { get; set; } // API eke
        public object Data { get; set; } //
        public string AccessToken { get; set; } // Authontication ekat use kranawa 

        // public ContentType ContentType { get; set; } = ContentType.Json
    }
}

ShoppingApplication.Webb/Models/ResponseDto.cs
namespace ShoppingApplication.Webb.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }  // result eka mokkd 
        public bool IsSuccess { get; set; } = true; // success da nadd ( default success kiyanne )
        public string Message { get; set; } = "";  // message ekak dennna 
    }
}

ShoppingApplication.Webb/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShoppingApplication.Webb.Models;
using ShoppingApplication.Webb.Service.IService;

namespace ShoppingApplication.Webb.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }


        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto>? list = new();

            ResponseDto? response = await _couponService.GetAllCouponsAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));
            }


            Console.WriteLine(list);
            return View(list);

        }
       
    }
}

ShoppingApplication.Webb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingApplication.Webb.Models;
using System.Diagnostics;

namespace ShoppingApplication.Webb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShoppingApplication.Webb/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>
@* @model List<CouponDto> *@
<p>@Model.Count()</p>
@* <p>@Model.</p> *@


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Coupons List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Coupon Code
					</th>
					<th>
						Discount Amount
					</th>
					<th>
						Minimum Amount
					</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				@foreach (var itm in Model)
				{
					@itm.CouponId
				}

				
					<tr>
						<td>
							
							
						</td>
						<td>
							

						</td>
						<td>
							

						</td>
						<td>
							<a class="btn btn-danger">
								<i class="bi bi-trash"></i>
							</a>
						</td>
					</tr>
				
			</tbody>

		</table>

	</div>

</div>

ShoppingApplication.Webb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShoppingApplication.Webb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingApplication.Webb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShoppingApplication.Webb.styles.css" asp-append-version="true" />


    <!-- Add the link for bootsrape Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingApplication.Webb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <!-- add the drop down from the bootstrape-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Managment
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                
                                <li><hr class="dropdown-divider"></li>
                               
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="text-center">
            Make <i class="bi bi-heart-fill"></i> with Online Shopping
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>